// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sacco.Modules.Members.Persistence;

#nullable disable

namespace Sacco.Migrations.Members
{
    [DbContext(typeof(MembersDbContext))]
    [Migration("20260914113238_MemberExit")]
    partial class MemberExit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("members")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sacco.Modules.Members.Domain.KycDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_reference");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_documents");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_kyc_documents_member_id");

                    b.ToTable("kyc_documents", "members");
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExitApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("exit_approved_by_user_id");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exit_reason");

                    b.Property<DateTimeOffset?>("ExitRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_requested_at");

                    b.Property<Guid?>("ExitRequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("exit_requested_by_user_id");

                    b.Property<string>("ExitSettlementJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("exit_settlement_json");

                    b.Property<DateTimeOffset?>("ExitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exited_at");

                    b.Property<DateOnly>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<string>("KycRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("kyc_rejection_reason");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer")
                        .HasColumnName("kyc_status");

                    b.Property<DateTimeOffset?>("KycVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_verified_at");

                    b.Property<Guid?>("KycVerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_verified_by_user_id");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("member_number");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_user_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_members_tenant_id");

                    b.HasIndex("TenantId", "KycStatus")
                        .HasDatabaseName("ix_members_tenant_id_kyc_status");

                    b.HasIndex("TenantId", "MemberNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_members_tenant_id_member_number");

                    b.ToTable("members", "members");
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.MemberNumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("NextValue")
                        .HasColumnType("integer")
                        .HasColumnName("next_value");

                    b.HasKey("TenantId")
                        .HasName("pk_member_number_sequences");

                    b.ToTable("member_number_sequences", "members");
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.MembershipApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BotCheckPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("bot_check_passed");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<Guid?>("CreatedMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_member_id");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("review_notes");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_fingerprint");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_membership_applications");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_membership_applications_tenant_id");

                    b.HasIndex("TenantId", "Status", "SubmittedAt")
                        .HasDatabaseName("ix_membership_applications_tenant_id_status_submitted_at");

                    b.ToTable("membership_applications", "members");
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.KycDocument", b =>
                {
                    b.HasOne("Sacco.Modules.Members.Domain.Member", null)
                        .WithMany("Documents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kyc_documents_members_member_id");
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.Member", b =>
                {
                    b.OwnsOne("Sacco.Modules.Members.Domain.PersonalDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("details_county");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("details_date_of_birth");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("details_email");

                            b1.Property<string>("EmployeeNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("details_employee_number");

                            b1.Property<string>("Employer")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("details_employer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_first_name");

                            b1.Property<int>("Gender")
                                .HasColumnType("integer")
                                .HasColumnName("details_gender");

                            b1.Property<string>("KraPin")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("details_kra_pin");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_middle_name");

                            b1.Property<string>("NationalIdNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("details_national_id_number");

                            b1.Property<string>("Occupation")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_occupation");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("details_phone_number");

                            b1.Property<string>("PostalAddress")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("details_postal_address");

                            b1.HasKey("MemberId");

                            b1.HasIndex("NationalIdNumber")
                                .HasDatabaseName("ix_members_details_national_id_number");

                            b1.HasIndex("PhoneNumber")
                                .HasDatabaseName("ix_members_details_phone_number");

                            b1.ToTable("members", "members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId")
                                .HasConstraintName("fk_members_members_id");
                        });

                    b.OwnsOne("Sacco.Modules.Members.Domain.NextOfKin", "NextOfKin", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("next_of_kin_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("next_of_kin_phone_number");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("next_of_kin_relationship");

                            b1.HasKey("MemberId");

                            b1.ToTable("members", "members");

                            b1.WithOwner()
                                .HasForeignKey("MemberId")
                                .HasConstraintName("fk_members_members_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("NextOfKin")
                        .IsRequired();
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.MembershipApplication", b =>
                {
                    b.OwnsOne("Sacco.Modules.Members.Domain.PersonalDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("MembershipApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("details_county");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("details_date_of_birth");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("details_email");

                            b1.Property<string>("EmployeeNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("details_employee_number");

                            b1.Property<string>("Employer")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("details_employer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_first_name");

                            b1.Property<int>("Gender")
                                .HasColumnType("integer")
                                .HasColumnName("details_gender");

                            b1.Property<string>("KraPin")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("details_kra_pin");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_middle_name");

                            b1.Property<string>("NationalIdNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("details_national_id_number");

                            b1.Property<string>("Occupation")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("details_occupation");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("details_phone_number");

                            b1.Property<string>("PostalAddress")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("details_postal_address");

                            b1.HasKey("MembershipApplicationId");

                            b1.HasIndex("NationalIdNumber")
                                .HasDatabaseName("ix_membership_applications_details_national_id_number");

                            b1.ToTable("membership_applications", "members");

                            b1.WithOwner()
                                .HasForeignKey("MembershipApplicationId")
                                .HasConstraintName("fk_membership_applications_membership_applications_id");
                        });

                    b.OwnsOne("Sacco.Modules.Members.Domain.NextOfKin", "NextOfKin", b1 =>
                        {
                            b1.Property<Guid>("MembershipApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("next_of_kin_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("next_of_kin_phone_number");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("next_of_kin_relationship");

                            b1.HasKey("MembershipApplicationId");

                            b1.ToTable("membership_applications", "members");

                            b1.WithOwner()
                                .HasForeignKey("MembershipApplicationId")
                                .HasConstraintName("fk_membership_applications_membership_applications_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("NextOfKin")
                        .IsRequired();
                });

            modelBuilder.Entity("Sacco.Modules.Members.Domain.Member", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
