// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sacco.Modules.Ledger.Persistence;

#nullable disable

namespace Sacco.Migrations.Ledger
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.GlAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsControlAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("is_control_account");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("NormalBalance")
                        .HasColumnType("integer")
                        .HasColumnName("normal_balance");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_gl_accounts");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_gl_accounts_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_gl_accounts_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_gl_accounts_tenant_id_code");

                    b.ToTable("gl_accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_gl_accounts_segment", "segment IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReversalOfEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_entry_id");

                    b.Property<Guid?>("ReversedByEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by_entry_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("ReversalOfEntryId")
                        .HasDatabaseName("ix_journal_entries_reversal_of_entry_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_journal_entries_tenant_id");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_tenant_id_reference");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_journal_entries_tenant_id_status");

                    b.HasIndex("TenantId", "ValueDate")
                        .HasDatabaseName("ix_journal_entries_tenant_id_value_date");

                    b.ToTable("journal_entries", "ledger");
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("GlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gl_account_code");

                    b.Property<Guid>("GlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid?>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("LedgerAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ledger_account_number");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Narrative")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("narrative");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("GlAccountId")
                        .HasDatabaseName("ix_journal_lines_gl_account_id");

                    b.HasIndex("LedgerAccountId")
                        .HasDatabaseName("ix_journal_lines_ledger_account_id");

                    b.HasIndex("JournalEntryId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_lines_journal_entry_id_line_number");

                    b.ToTable("journal_lines", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_journal_lines_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_journal_lines_segment", "segment IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("ControlGlAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("control_gl_account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("HeldAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("held_amount");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_code");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasIndex("ControlGlAccountId")
                        .HasDatabaseName("ix_ledger_accounts_control_gl_account_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ledger_accounts_tenant_id");

                    b.HasIndex("TenantId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_tenant_id_account_number");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("ix_ledger_accounts_tenant_id_member_id");

                    b.ToTable("ledger_accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_held_non_negative", "held_amount >= 0");

                            t.HasCheckConstraint("ck_ledger_accounts_segment", "segment IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.GlAccount", b =>
                {
                    b.HasOne("Sacco.Modules.Ledger.Domain.GlAccount", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gl_accounts_gl_accounts_parent_id");
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.HasOne("Sacco.Modules.Ledger.Domain.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reversal_of_entry_id");
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.JournalLine", b =>
                {
                    b.HasOne("Sacco.Modules.Ledger.Domain.GlAccount", null)
                        .WithMany()
                        .HasForeignKey("GlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_gl_accounts_gl_account_id");

                    b.HasOne("Sacco.Modules.Ledger.Domain.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.HasOne("Sacco.Modules.Ledger.Domain.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_lines_ledger_accounts_ledger_account_id");
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.LedgerAccount", b =>
                {
                    b.HasOne("Sacco.Modules.Ledger.Domain.GlAccount", null)
                        .WithMany()
                        .HasForeignKey("ControlGlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_accounts_gl_accounts_control_gl_account_id");
                });

            modelBuilder.Entity("Sacco.Modules.Ledger.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
