using Sacco.Shared.Tenancy;

namespace Sacco.Modules.Savings.Domain;

/// <summary>
/// A member paying to see a fee-gated account's balance (ADR 0015). It opens a short reveal window; while it is open,
/// self-service shows that account's balance and statement. <see cref="IdempotencyKey"/> is generated by the app per tap,
/// so a retried request never charges twice.
/// </summary>
public class BalanceEnquiry : TenantEntity
{
    private BalanceEnquiry() { }

    public Guid MemberId { get; private set; }
    public string AccountNumber { get; private set; } = string.Empty;
    public string IdempotencyKey { get; private set; } = string.Empty;
    public decimal Fee { get; private set; }
    public Guid FeeRuleId { get; private set; }
    public string ChargedAccountNumber { get; private set; } = string.Empty;
    public string JournalReference { get; private set; } = string.Empty;
    public Guid RequestedByUserId { get; private set; }
    public DateTimeOffset RequestedAt { get; private set; }
    public DateTimeOffset VisibleUntil { get; private set; }

    public static BalanceEnquiry Record(Guid id, Guid tenantId, Guid memberId, string accountNumber, string idempotencyKey, decimal fee, Guid feeRuleId,
        string chargedAccountNumber, string journalReference, Guid requestedBy, DateTimeOffset now, TimeSpan window)
        => new()
        {
            Id = id, TenantId = tenantId, MemberId = memberId, AccountNumber = accountNumber, IdempotencyKey = idempotencyKey, Fee = fee, FeeRuleId = feeRuleId,
            ChargedAccountNumber = chargedAccountNumber, JournalReference = journalReference, RequestedByUserId = requestedBy, RequestedAt = now, VisibleUntil = now + window,
        };
}
