// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sacco.Modules.Lending.Persistence;

#nullable disable

namespace Sacco.Migrations.Lending
{
    [DbContext(typeof(LendingDbContext))]
    partial class LendingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lending")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.AgingBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<int>("MinDaysInArrears")
                        .HasColumnType("integer")
                        .HasColumnName("min_days_in_arrears");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProvisionRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("provision_rate_bps");

                    b.HasKey("Id")
                        .HasName("pk_aging_buckets");

                    b.HasIndex("ConfigId")
                        .HasDatabaseName("ix_aging_buckets_config_id");

                    b.ToTable("aging_buckets", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<string>("AppraisalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("appraisal_notes");

                    b.Property<DateTimeOffset?>("AppraisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appraised_at");

                    b.Property<Guid?>("AppraisedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("appraised_by_user_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("BureauConsentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bureau_consent_at");

                    b.Property<string>("BureauConsentText")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("bureau_consent_text");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("DisbursedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disbursed_at");

                    b.Property<Guid?>("DisbursedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("disbursed_by_user_id");

                    b.Property<string>("DisbursementAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("disbursement_account_number");

                    b.Property<DateOnly?>("DisbursementDate")
                        .HasColumnType("date")
                        .HasColumnName("disbursement_date");

                    b.Property<int>("InterestMethod")
                        .HasColumnType("integer")
                        .HasColumnName("interest_method");

                    b.Property<int>("InterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("interest_rate_bps");

                    b.Property<string>("LedgerAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ledger_account_number");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("loan_number");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("PledgedDepositsAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pledged_deposits_account_number");

                    b.Property<decimal>("PledgedDepositsAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pledged_deposits_amount");

                    b.Property<decimal>("ProcessingFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("processing_fee");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_code");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("RestructureCount")
                        .HasColumnType("integer")
                        .HasColumnName("restructure_count");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.HasKey("Id")
                        .HasName("pk_loans");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_loans_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_loans_tenant_id");

                    b.HasIndex("TenantId", "LoanNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_loans_tenant_id_loan_number");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("ix_loans_tenant_id_member_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_loans_tenant_id_status");

                    b.ToTable("loans", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_notes");

                    b.Property<decimal?>("InterestReversed")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_reversed");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("loan_number");

                    b.Property<int?>("NewInterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("new_interest_rate_bps");

                    b.Property<int?>("NewTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("new_term_months");

                    b.Property<decimal?>("PrincipalWrittenOff")
                        .HasColumnType("numeric")
                        .HasColumnName("principal_written_off");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_loan_adjustments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_loan_adjustments_tenant_id");

                    b.HasIndex("LoanId", "Status")
                        .HasDatabaseName("ix_loan_adjustments_loan_id_status");

                    b.ToTable("loan_adjustments", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_loan_approvals");

                    b.HasIndex("LoanId", "ApproverUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_loan_approvals_loan_id_approver_user_id");

                    b.ToTable("loan_approvals", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanCreditScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BureauNarrative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bureau_narrative");

                    b.Property<string>("BureauReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bureau_reference");

                    b.Property<int>("BureauStatus")
                        .HasColumnType("integer")
                        .HasColumnName("bureau_status");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("ComputedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("computed_by_user_id");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("factors_json");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("grade");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("Recommendation")
                        .HasColumnType("integer")
                        .HasColumnName("recommendation");

                    b.Property<string>("RecommendationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recommendation_reason");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("ScorecardUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scorecard_updated_at");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_loan_credit_scores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_loan_credit_scores_tenant_id");

                    b.HasIndex("LoanId", "ComputedAt")
                        .HasDatabaseName("ix_loan_credit_scores_loan_id_computed_at");

                    b.ToTable("loan_credit_scores", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanGuarantor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("AmountGuaranteed")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_guaranteed");

                    b.Property<string>("DepositsAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("deposits_account_number");

                    b.Property<Guid>("GuarantorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("guarantor_member_id");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_loan_guarantors");

                    b.HasIndex("GuarantorMemberId")
                        .HasDatabaseName("ix_loan_guarantors_guarantor_member_id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_loan_guarantors_loan_id");

                    b.ToTable("loan_guarantors", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanNumberSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("NextValue")
                        .HasColumnType("integer")
                        .HasColumnName("next_value");

                    b.HasKey("TenantId")
                        .HasName("pk_loan_number_sequences");

                    b.ToTable("loan_number_sequences", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<int>("CommitteeApprovalsRequired")
                        .HasColumnType("integer")
                        .HasColumnName("committee_approvals_required");

                    b.Property<decimal>("CommitteeThreshold")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("committee_threshold");

                    b.Property<string>("ControlGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_gl_account_code");

                    b.Property<decimal>("DepositMultiplier")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("deposit_multiplier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FeeIncomeGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_income_gl_account_code");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("grace_period_days");

                    b.Property<string>("InterestIncomeGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interest_income_gl_account_code");

                    b.Property<int>("InterestMethod")
                        .HasColumnType("integer")
                        .HasColumnName("interest_method");

                    b.Property<int>("InterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("interest_rate_bps");

                    b.Property<string>("InterestReceivableGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interest_receivable_gl_account_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_amount");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("max_term_months");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_amount");

                    b.Property<int>("MinGuarantors")
                        .HasColumnType("integer")
                        .HasColumnName("min_guarantors");

                    b.Property<int>("MinMembershipMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_membership_months");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_term_months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("ProcessingFeeBps")
                        .HasColumnType("integer")
                        .HasColumnName("processing_fee_bps");

                    b.Property<string>("ProvisionExpenseGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provision_expense_gl_account_code");

                    b.Property<string>("ProvisionGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provision_gl_account_code");

                    b.Property<bool>("RequiresGuarantors")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_guarantors");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_code");

                    b.ToTable("products", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Source")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_config");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_provisioning_config_tenant_id");

                    b.ToTable("provisioning_config", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ArrearsAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("arrears_amount");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bucket");

                    b.Property<int>("DaysInArrears")
                        .HasColumnType("integer")
                        .HasColumnName("days_in_arrears");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("loan_number");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("outstanding_principal");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_code");

                    b.Property<int>("ProvisionRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("provision_rate_bps");

                    b.Property<decimal>("ProvisionRequired")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("provision_required");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_lines");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_provisioning_lines_run_id");

                    b.ToTable("provisioning_lines", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("date")
                        .HasColumnName("as_of");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("ComputedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("computed_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalOutstanding")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_outstanding");

                    b.Property<decimal>("TotalProvisionRequired")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_provision_required");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_runs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_provisioning_runs_tenant_id");

                    b.HasIndex("TenantId", "AsOf")
                        .HasDatabaseName("ix_provisioning_runs_tenant_id_as_of");

                    b.ToTable("provisioning_runs", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.RepaymentInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("InterestAccrued")
                        .HasColumnType("boolean")
                        .HasColumnName("interest_accrued");

                    b.Property<decimal>("InterestDue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest_due");

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest_paid");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("PrincipalDue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal_due");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal_paid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_repayment_schedule");

                    b.HasIndex("DueDate", "Status")
                        .HasDatabaseName("ix_repayment_schedule_due_date_status");

                    b.HasIndex("LoanId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_repayment_schedule_loan_id_number");

                    b.ToTable("repayment_schedule", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.Scorecard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApproveThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("approve_threshold");

                    b.Property<bool>("DeclineIfBureauListed")
                        .HasColumnType("boolean")
                        .HasColumnName("decline_if_bureau_listed");

                    b.Property<int>("ReferThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("refer_threshold");

                    b.Property<string>("Source")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_scorecards");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_scorecards_tenant_id");

                    b.ToTable("scorecards", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ScorecardFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer")
                        .HasColumnName("max_points");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uuid")
                        .HasColumnName("scorecard_id");

                    b.HasKey("Id")
                        .HasName("pk_scorecard_factors");

                    b.HasIndex("ScorecardId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_scorecard_factors_scorecard_id_key");

                    b.ToTable("scorecard_factors", "lending");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.AgingBucket", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.ProvisioningConfig", null)
                        .WithMany("Buckets")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aging_buckets_provisioning_config_config_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.Loan", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.LoanProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loans_products_product_id");

                    b.OwnsOne("Sacco.Modules.Lending.Domain.EligibilitySnapshot", "Eligibility", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("BosaDeposits")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("eligibility_bosa_deposits");

                            b1.Property<int>("ContributionMonths")
                                .HasColumnType("integer")
                                .HasColumnName("eligibility_contribution_months");

                            b1.Property<decimal>("DepositMultiplier")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("eligibility_deposit_multiplier");

                            b1.Property<decimal>("ExistingOutstanding")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("eligibility_existing_outstanding");

                            b1.Property<decimal>("MaxEligibleAmount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("eligibility_max_eligible_amount");

                            b1.Property<int>("MembershipMonths")
                                .HasColumnType("integer")
                                .HasColumnName("eligibility_membership_months");

                            b1.Property<decimal>("Shares")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("eligibility_shares");

                            b1.HasKey("LoanId");

                            b1.ToTable("loans", "lending");

                            b1.WithOwner()
                                .HasForeignKey("LoanId")
                                .HasConstraintName("fk_loans_loans_id");
                        });

                    b.Navigation("Eligibility")
                        .IsRequired();
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanApproval", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.Loan", null)
                        .WithMany("Approvals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loan_approvals_loans_loan_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanGuarantor", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.Loan", null)
                        .WithMany("Guarantors")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loan_guarantors_loans_loan_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.LoanProduct", b =>
                {
                    b.OwnsOne("Sacco.Shared.Domain.PublicListing", "Listing", b1 =>
                        {
                            b1.Property<Guid>("LoanProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AmountNote")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("listing_amount_note");

                            b1.Property<string>("ApplicationFormUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("listing_application_form_url");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("listing_display_order");

                            b1.PrimitiveCollection<List<string>>("Features")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("listing_features");

                            b1.PrimitiveCollection<List<string>>("Requirements")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("listing_requirements");

                            b1.Property<bool>("ShowOnPublicSite")
                                .HasColumnType("boolean")
                                .HasColumnName("listing_show_on_public_site");

                            b1.HasKey("LoanProductId");

                            b1.ToTable("products", "lending");

                            b1.WithOwner()
                                .HasForeignKey("LoanProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Listing")
                        .IsRequired();
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningLine", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.ProvisioningRun", null)
                        .WithMany("Lines")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_lines_provisioning_runs_run_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.RepaymentInstallment", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.Loan", null)
                        .WithMany("Schedule")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repayment_schedule_loans_loan_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ScorecardFactor", b =>
                {
                    b.HasOne("Sacco.Modules.Lending.Domain.Scorecard", null)
                        .WithMany("Factors")
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scorecard_factors_scorecards_scorecard_id");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.Loan", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Guarantors");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningConfig", b =>
                {
                    b.Navigation("Buckets");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.ProvisioningRun", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Sacco.Modules.Lending.Domain.Scorecard", b =>
                {
                    b.Navigation("Factors");
                });
#pragma warning restore 612, 618
        }
    }
}
