<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Sacco.Shared/Sacco.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Open.IdentityServer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>
</Project>
