// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sacco.Modules.Payments.Persistence;

#nullable disable

namespace Sacco.Migrations.Payments
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sacco.Modules.Payments.Domain.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CallbackCount")
                        .HasColumnType("integer")
                        .HasColumnName("callback_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("counterparty");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LedgerJournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_journal_entry_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Narrative")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("narrative");

                    b.Property<string>("OurReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("our_reference");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_request_id");

                    b.Property<string>("ProviderTransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_transaction_reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_transactions_tenant_id");

                    b.HasIndex("TenantId", "OurReference")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_tenant_id_our_reference");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_transactions_tenant_id_status");

                    b.HasIndex("TenantId", "Provider", "ProviderRequestId")
                        .HasDatabaseName("ix_transactions_tenant_id_provider_provider_request_id");

                    b.ToTable("transactions", "payments");
                });

            modelBuilder.Entity("Sacco.Modules.Payments.Domain.ProcessedProviderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_transaction_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_processed_provider_transactions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_processed_provider_transactions_tenant_id");

                    b.HasIndex("Provider", "ProviderTransactionReference")
                        .IsUnique()
                        .HasDatabaseName("ux_processed_provider_transactions_reference");

                    b.ToTable("processed_provider_transactions", "payments");
                });

            modelBuilder.Entity("Sacco.Modules.Payments.Domain.PaymentTransaction", b =>
                {
                    b.OwnsOne("Sacco.Modules.Payments.Domain.PaymentPurpose", "Purpose", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccountNumber")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("purpose_account_number");

                            b1.Property<string>("LoanNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("purpose_loan_number");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("purpose_type");

                            b1.Property<Guid?>("WithdrawalId")
                                .HasColumnType("uuid")
                                .HasColumnName("purpose_withdrawal_id");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("transactions", "payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Purpose")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
