// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sacco.Modules.Savings.Persistence;

#nullable disable

namespace Sacco.Migrations.Savings
{
    [DbContext(typeof(SavingsDbContext))]
    [Migration("20260917051931_FeeMatrixAndBalanceEnquiries")]
    partial class FeeMatrixAndBalanceEnquiries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("savings")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.BalanceEnquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<string>("ChargedAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("charged_account_number");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee");

                    b.Property<Guid>("FeeRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_rule_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("JournalReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("journal_reference");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("VisibleUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visible_until");

                    b.HasKey("Id")
                        .HasName("pk_balance_enquiries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_balance_enquiries_tenant_id");

                    b.HasIndex("TenantId", "MemberId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_balance_enquiries_tenant_id_member_id_idempotency_key");

                    b.HasIndex("TenantId", "MemberId", "VisibleUntil")
                        .HasDatabaseName("ix_balance_enquiries_tenant_id_member_id_visible_until");

                    b.ToTable("balance_enquiries", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.DividendDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("DeclaredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_at");

                    b.Property<Guid>("DeclaredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by_user_id");

                    b.Property<int>("DepositInterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_interest_rate_bps");

                    b.Property<int>("FinancialYear")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("ShareDividendRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("share_dividend_rate_bps");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalDepositInterest")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_deposit_interest");

                    b.Property<decimal>("TotalShareDividend")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_share_dividend");

                    b.Property<decimal>("TotalWithholdingTax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_withholding_tax");

                    b.Property<int>("WithholdingTaxBps")
                        .HasColumnType("integer")
                        .HasColumnName("withholding_tax_bps");

                    b.HasKey("Id")
                        .HasName("pk_dividend_declarations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dividend_declarations_tenant_id");

                    b.HasIndex("TenantId", "FinancialYear")
                        .HasDatabaseName("ix_dividend_declarations_tenant_id_financial_year");

                    b.ToTable("dividend_declarations", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.DividendLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<decimal>("DepositBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_balance");

                    b.Property<decimal>("DepositInterest")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_interest");

                    b.Property<string>("DepositsAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("deposits_account_number");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("JournalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("journal_reference");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("PayoutAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payout_account_number");

                    b.Property<decimal>("ShareBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("share_balance");

                    b.Property<decimal>("ShareDividend")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("share_dividend");

                    b.Property<string>("SharesAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shares_account_number");

                    b.Property<decimal>("WithholdingTax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("withholding_tax");

                    b.HasKey("Id")
                        .HasName("pk_dividend_lines");

                    b.HasIndex("DeclarationId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_dividend_lines_declaration_id_member_id");

                    b.ToTable("dividend_lines", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.FeeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("FeeIncomeGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_income_gl_account_code");

                    b.Property<int>("FeeIncomeSegment")
                        .HasColumnType("integer")
                        .HasColumnName("fee_income_segment");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_amount");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_amount");

                    b.Property<decimal?>("MaxCharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_charge");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_amount");

                    b.Property<decimal?>("MinCharge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_charge");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_code");

                    b.Property<int?>("RateBps")
                        .HasColumnType("integer")
                        .HasColumnName("rate_bps");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_rule_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_fee_rules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_fee_rules_tenant_id");

                    b.HasIndex("TenantId", "Status", "TransactionType")
                        .HasDatabaseName("ix_fee_rules_tenant_id_status_transaction_type");

                    b.ToTable("fee_rules", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.FeeTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("charge");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<decimal?>("UpTo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("up_to");

                    b.HasKey("Id")
                        .HasName("pk_fee_tiers");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_fee_tiers_rule_id");

                    b.ToTable("fee_tiers", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("InterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("interest_rate_bps");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("maturity_date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("PayoutAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payout_account_number");

                    b.Property<decimal?>("Principal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_code");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_accounts_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounts_tenant_id");

                    b.HasIndex("TenantId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_tenant_id_account_number");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("ix_accounts_tenant_id_member_id");

                    b.ToTable("accounts", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.SavingsProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountSuffix")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("account_suffix");

                    b.Property<bool>("AllowsWithdrawals")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_withdrawals");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("ControlGlAccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_gl_account_code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FeeIncomeGlAccountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_income_gl_account_code");

                    b.Property<string>("InterestExpenseGlAccountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interest_expense_gl_account_code");

                    b.Property<int>("InterestRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("interest_rate_bps");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<decimal>("MinimumBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_balance");

                    b.Property<decimal>("MinimumOpeningDeposit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_opening_deposit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.Property<decimal>("TellerWithdrawalLimit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("teller_withdrawal_limit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<decimal>("WithdrawalFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("withdrawal_fee");

                    b.Property<int>("WithdrawalNoticeDays")
                        .HasColumnType("integer")
                        .HasColumnName("withdrawal_notice_days");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_code");

                    b.ToTable("products", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.ShareListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BuyerFosaAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("buyer_fosa_account_number");

                    b.Property<Guid?>("BuyerMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_member_id");

                    b.Property<string>("BuyerSharesAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("buyer_shares_account_number");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("JournalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("journal_reference");

                    b.Property<DateTimeOffset>("ListedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listed_at");

                    b.Property<Guid>("ListedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("listed_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SellerFosaAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("seller_fosa_account_number");

                    b.Property<Guid>("SellerMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_member_id");

                    b.Property<string>("SellerSharesAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("seller_shares_account_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_share_listings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_share_listings_tenant_id");

                    b.HasIndex("TenantId", "BuyerMemberId")
                        .HasDatabaseName("ix_share_listings_tenant_id_buyer_member_id");

                    b.HasIndex("TenantId", "SellerMemberId")
                        .HasDatabaseName("ix_share_listings_tenant_id_seller_member_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_share_listings_tenant_id_status");

                    b.ToTable("share_listings", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee");

                    b.Property<string>("FeeGlAccountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fee_gl_account_code");

                    b.Property<Guid?>("FeeRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_rule_id");

                    b.Property<int?>("FeeSegment")
                        .HasColumnType("integer")
                        .HasColumnName("fee_segment");

                    b.Property<string>("JournalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("journal_reference");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Narrative")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("narrative");

                    b.Property<DateOnly>("NoticeExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("notice_expires_on");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_user_id");

                    b.Property<string>("PayoutDestination")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payout_destination");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_withdrawal_requests");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_withdrawal_requests_tenant_id");

                    b.HasIndex("TenantId", "AccountNumber")
                        .HasDatabaseName("ix_withdrawal_requests_tenant_id_account_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_withdrawal_requests_tenant_id_status");

                    b.ToTable("withdrawal_requests", "savings");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.DividendLine", b =>
                {
                    b.HasOne("Sacco.Modules.Savings.Domain.DividendDeclaration", null)
                        .WithMany("Lines")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dividend_lines_dividend_declarations_declaration_id");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.FeeTier", b =>
                {
                    b.HasOne("Sacco.Modules.Savings.Domain.FeeRule", null)
                        .WithMany("Tiers")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fee_tiers_fee_rules_rule_id");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.SavingsAccount", b =>
                {
                    b.HasOne("Sacco.Modules.Savings.Domain.SavingsProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_products_product_id");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.DividendDeclaration", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Sacco.Modules.Savings.Domain.FeeRule", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
