<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Sacco.Shared/Sacco.Shared.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Platform/Sacco.Modules.Platform.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Ledger/Sacco.Modules.Ledger.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Members/Sacco.Modules.Members.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Savings/Sacco.Modules.Savings.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Lending/Sacco.Modules.Lending.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Payments/Sacco.Modules.Payments.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Reporting/Sacco.Modules.Reporting.csproj" />
    <ProjectReference Include="../../src/Sacco.Modules.Identity/Sacco.Modules.Identity.csproj" />
    <ProjectReference Include="../../src/Sacco.Migrations/Sacco.Migrations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Bogus" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
